### ISSUE TITLE
Easier way to see validation error log for a provider

### ISSUE THREAD

**Issue by rartino** [Materials-Consortia/providers-dashboard#8]
(Hey, awesome job in general with the providers dashboard and validation etc.!)

If we are publishing validation reports for every provider on their detail page, it seems helpful and a nice thing to also provide details on the validation errors. (In a more user-friendly way than digging down in the providers-dashboard actions log...)

Also, this probably should be filed as a bug against the optimade-validator, but I don't think the validator should be able to reject validation without some form of more detailed explanation. See, e.g., the action log here:

  https://github.com/Materials-Consortia/providers-dashboard/runs/1654634459?check_suite_focus=true 

In that log, under "Make pages", omdb gets an 'x' in the first test (at least, that is how I interpret that row of dots). The reason was a bug in serving info under /v1; but the validator output gives no explanation on this.

**Comment by ml-evs** [comment]
Hi @rartino, I agree that it would be great to get the validator output to fill in that page, the data is all there inside the Python code, it would just need someone to add it to the UI.

On the second point, running the validator manually indicates that http://optimade.openmaterialsdb.se/v1 is causing the validator to crash (hence the lack of helpful errors...). 

The problem seems to be that http://optimade.openmaterialsdb.se/v1/info returns a length-1 array under `data`, rather than the top-level dictionary itself. I'm actually working on the validator a bit today, I think this is the one remaining hardcoded "critical error" so I'll try to sort it out.
